import type {
  Ember,
  Hearth,
  Keepsake,
  Letter,
  Neighborhood,
  Person,
  Spark,
} from "./types";

const hour = 60 * 60 * 1000;
const now = Date.now();

export const YOU_ID = "you";

export const neighborhoods: Neighborhood[] = [
  {
    id: "meadow-edge",
    name: "Meadow Edge",
    epithet: "Where the peninsula forgets the road",
    description:
      "Long grass, cassette hiss, and cottages that face the harbor instead of each other. People here leave doors unlatched and conversations unfinished on purpose.",
    climate: "Salt wind, late gold",
    cover: "/images/neighborhoods/meadow-edge.jpg",
    accent: "meadow",
  },
  {
    id: "conservatory",
    name: "The Conservatory",
    epithet: "Glass, soil, and patience",
    description:
      "A climate of misted panes and terracotta. Dwellings here are tended like plants — slowly, with both hands, and never for an audience.",
    climate: "Humid green, filtered sun",
    cover: "/images/neighborhoods/conservatory.jpg",
    accent: "leaf",
  },
  {
    id: "hearth-grain",
    name: "Hearth & Grain",
    epithet: "The hours after the ovens are lit",
    description:
      "Night kitchens, steam, copper, and the kind of talk that only happens when everyone is a little tired. Bread is a public language.",
    climate: "Warmth, flour, lampglow",
    cover: "/images/neighborhoods/hearth-grain.jpg",
    accent: "ember",
  },
  {
    id: "night-terrace",
    name: "Night Terrace",
    epithet: "Roofs, film, and unfinished maps",
    description:
      "The high side of the peninsula. People gather less often and stay longer. Looking is considered a form of company.",
    climate: "Blue hour, paper, silence",
    cover: "/images/neighborhoods/night-terrace.jpg",
    accent: "star",
  },
];

export const people: Person[] = [
  {
    id: YOU_ID,
    name: "You",
    craft: "Wanderer",
    letter:
      "I just crossed the threshold. The rooms are still empty. If you visit, leave something small — I am still learning how to host.",
    bio: "A newly lit dwelling at the edge of the atlas. Unfinished on purpose.",
    portrait: "/images/portraits/you.jpg",
    cover: "/images/dwellings/you.jpg",
    neighborhoodId: "meadow-edge",
    mood: "threshold",
    x: 82,
    y: 46,
    isYou: true,
  },
  {
    id: "mira",
    name: "Mira Solène",
    craft: "Ceramicist",
    letter:
      "If you come in with wet shoes, that is fine. The floor is already clay. Sit with a bowl that isn't finished. I like company that does not need to be useful.",
    bio: "Throws vessels that are meant to be held, not displayed. Keeps a guest wheel by the window.",
    portrait: "/images/portraits/mira.jpg",
    cover: "/images/dwellings/mira.jpg",
    neighborhoodId: "conservatory",
    mood: "clay",
    x: 34,
    y: 48,
  },
  {
    id: "jonah",
    name: "Jonah Hale",
    craft: "Field recordist",
    letter:
      "I am often out. If the shed is empty, the meadow is not. Borrow the headphones on the hook. The best hour is the one just before the insects start.",
    bio: "Collects the sound of places so they can be visited twice. Speaks softly, records loudly.",
    portrait: "/images/portraits/jonah.jpg",
    cover: "/images/dwellings/jonah.jpg",
    neighborhoodId: "meadow-edge",
    mood: "dusk",
    x: 24,
    y: 72,
  },
  {
    id: "aya",
    name: "Aya Nakamura",
    craft: "Night baker",
    letter:
      "The door is unlocked from eleven until the first loaves come out. You do not have to talk. You can sit at the marble and be warm. If you are hungry I will know.",
    bio: "Bakes when the peninsula is asleep. Believes tired people tell the truth.",
    portrait: "/images/portraits/aya.jpg",
    cover: "/images/dwellings/aya.jpg",
    neighborhoodId: "hearth-grain",
    mood: "ember",
    x: 58,
    y: 50,
  },
  {
    id: "leo",
    name: "Leo Vargas",
    craft: "Botanist",
    letter:
      "Please do not tap the glass. The ferns startle. Walk the long way around the banana and you will find a chair that faces the mist. Stay until something new unfurls. It might take a week.",
    bio: "Keeps a public conservatory and a private list of plants that have outlived their owners.",
    portrait: "/images/portraits/leo.jpg",
    cover: "/images/dwellings/leo.jpg",
    neighborhoodId: "conservatory",
    mood: "chlorophyll",
    x: 40,
    y: 36,
  },
  {
    id: "sable",
    name: "Sable Quinn",
    craft: "Letterpress printer",
    letter:
      "The press is louder than I am. If you want to talk, write it first and we can set it in type. Visitors who ink their fingers are always welcome back.",
    bio: "Prints other people's letters so they have weight. Collects orphaned sorts.",
    portrait: "/images/portraits/sable.jpg",
    cover: "/images/dwellings/sable.jpg",
    neighborhoodId: "night-terrace",
    mood: "ink",
    x: 50,
    y: 54,
  },
  {
    id: "rafi",
    name: "Rafi Okonkwo",
    craft: "Poet & astronomer",
    letter:
      "The roof holds two. Bring a coat. I do not narrate the sky. If a satellite passes we can pretend it is a wish, once, and then we will be quiet again.",
    bio: "Writes the kind of poems that fit on a matchbook. Keeps a telescope that is better at listening than looking.",
    portrait: "/images/portraits/rafi.jpg",
    cover: "/images/dwellings/rafi.jpg",
    neighborhoodId: "night-terrace",
    mood: "starlight",
    x: 74,
    y: 22,
  },
  {
    id: "elena",
    name: "Elena Voss",
    craft: "Slow-cinema maker",
    letter:
      "There is a chair in the darkroom that is not for watching me work. It is for sitting in red light until your eyes change. If you need to speak, whisper. Silver is shy.",
    bio: "Films people doing almost nothing until it becomes everything. Develops by hand.",
    portrait: "/images/portraits/elena.jpg",
    cover: "/images/dwellings/elena.jpg",
    neighborhoodId: "night-terrace",
    mood: "silver",
    x: 66,
    y: 40,
  },
  {
    id: "kai",
    name: "Kai Chen",
    craft: "Tea blender",
    letter:
      "Steam hour is four o'clock, whether or not anyone comes. The first cup is always for the room. If you stay for a second, tell me something you have been steeping.",
    bio: "Blends teas the way some people compose letters. Believes every visit should have a temperature.",
    portrait: "/images/portraits/kai.jpg",
    cover: "/images/dwellings/kai.jpg",
    neighborhoodId: "hearth-grain",
    mood: "steam",
    x: 46,
    y: 62,
  },
];

export const sparks: Spark[] = [
  {
    id: "sp-mira-1",
    dwellingId: "mira",
    title: "A bowl that leaked",
    body: "I threw six bowls this morning and one of them would not hold water. I kept it anyway. Some vessels are for carrying. Some are for teaching the hands to slow down.",
    image: "/images/sparks/mira-1.jpg",
    createdAt: now - 5 * hour,
    mood: "clay",
  },
  {
    id: "sp-mira-2",
    dwellingId: "mira",
    title: "Guest wheel",
    body: "Someone sat at the extra wheel yesterday and made a lid with no pot. I put it on the shelf. If they come back they can finish the sentence.",
    image: "/images/sparks/mira-2.jpg",
    createdAt: now - 30 * hour,
    mood: "clay",
  },
  {
    id: "sp-jonah-1",
    dwellingId: "jonah",
    title: "The meadow before insects",
    body: "Twenty-three minutes of almost nothing: cloth, wind, one distant boat. I will not put it on a map. You have to walk here for it.",
    image: "/images/sparks/jonah-1.jpg",
    createdAt: now - 8 * hour,
    mood: "dusk",
  },
  {
    id: "sp-jonah-2",
    dwellingId: "jonah",
    title: "Borrowed headphones",
    body: "They are still on the hook. Whoever had them last left the volume very low, which I take as a form of manners.",
    image: "/images/sparks/jonah-2.jpg",
    createdAt: now - 52 * hour,
    mood: "dusk",
  },
  {
    id: "sp-aya-1",
    dwellingId: "aya",
    title: "First loaves",
    body: "The peninsula smells like fennel after midnight. I left two loaves on the sill for whoever is walking home later than they meant to.",
    image: "/images/sparks/aya-1.jpg",
    createdAt: now - 3 * hour,
    mood: "ember",
  },
  {
    id: "sp-aya-2",
    dwellingId: "aya",
    title: "The marble",
    body: "A man sat here for an hour and did not speak. When he left he wiped the flour from the edge, which is how I knew he had been a guest and not a ghost.",
    image: "/images/sparks/aya-2.jpg",
    createdAt: now - 27 * hour,
    mood: "ember",
  },
  {
    id: "sp-leo-1",
    dwellingId: "leo",
    title: "The fern that startles",
    body: "It is not shy. It is particular. If you enter slowly it will stay open. I have started to treat people the same way.",
    image: "/images/sparks/leo-1.jpg",
    createdAt: now - 12 * hour,
    mood: "chlorophyll",
  },
  {
    id: "sp-leo-2",
    dwellingId: "leo",
    title: "A plant with no owner",
    body: "I inherited a citrus from a woman who moved inland. It still fruits toward her old window. I will not turn the pot.",
    image: "/images/sparks/leo-2.jpg",
    createdAt: now - 70 * hour,
    mood: "chlorophyll",
  },
  {
    id: "sp-sable-1",
    dwellingId: "sable",
    title: "Orphaned sorts",
    body: "I found a drawer of Qs with no Us. I am printing a broadsheet of questions that do not want answers.",
    image: "/images/sparks/sable-1.jpg",
    createdAt: now - 9 * hour,
    mood: "ink",
  },
  {
    id: "sp-sable-2",
    dwellingId: "sable",
    title: "Weight",
    body: "A letter is different once it has been pressed. You can feel the sentence with your thumb. I wish more of us would send things that have a body.",
    image: "/images/sparks/sable-2.jpg",
    createdAt: now - 44 * hour,
    mood: "ink",
  },
  {
    id: "sp-rafi-1",
    dwellingId: "rafi",
    title: "Matchbook",
    body: "Tonight's poem, entire: / the satellite thought it was a star / and for three seconds / so did we.",
    image: "/images/sparks/rafi-1.jpg",
    createdAt: now - 6 * hour,
    mood: "starlight",
  },
  {
    id: "sp-rafi-2",
    dwellingId: "rafi",
    title: "Two coats",
    body: "I keep a second coat on the peg for the person who always forgets. It has never been Mira. It is always Mira.",
    image: "/images/sparks/rafi-2.jpg",
    createdAt: now - 38 * hour,
    mood: "starlight",
  },
  {
    id: "sp-elena-1",
    dwellingId: "elena",
    title: "Four minutes of a hand",
    body: "I filmed Kai pouring tea until the steam left the frame. Nothing happens and then it does. This is the only plot I trust.",
    image: "/images/sparks/elena-1.jpg",
    createdAt: now - 14 * hour,
    mood: "silver",
  },
  {
    id: "sp-elena-2",
    dwellingId: "elena",
    title: "Safelight",
    body: "People look different in red. Kinder, or more like themselves. I am not sure which. Stay until you know.",
    image: "/images/sparks/elena-2.jpg",
    createdAt: now - 61 * hour,
    mood: "silver",
  },
  {
    id: "sp-kai-1",
    dwellingId: "kai",
    title: "Steam hour",
    body: "Today's blend is roasted barley, osmanthus, a little smoked hay. It tastes like a field remembering a fire.",
    image: "/images/sparks/kai-1.jpg",
    createdAt: now - 2 * hour,
    mood: "steam",
  },
  {
    id: "sp-kai-2",
    dwellingId: "kai",
    title: "The first cup",
    body: "I poured it for the empty stool. When Aya came later she drank it without asking whose it was. That is the correct use of a first cup.",
    image: "/images/sparks/kai-2.jpg",
    createdAt: now - 20 * hour,
    mood: "steam",
  },
];

export const keepsakes: Keepsake[] = [
  {
    id: "k1",
    dwellingId: "mira",
    fromId: "kai",
    kind: "steam",
    note: "For the bowl that leaked. Some things are allowed to not hold.",
    image: "/images/keepsakes/steam.jpg",
    createdAt: now - 4 * hour,
  },
  {
    id: "k2",
    dwellingId: "aya",
    fromId: "jonah",
    kind: "stone",
    note: "From the path behind the bakery. It was warm from the chimney.",
    image: "/images/keepsakes/stone.jpg",
    createdAt: now - 7 * hour,
  },
  {
    id: "k3",
    dwellingId: "leo",
    fromId: "mira",
    kind: "bowl",
    note: "Unglazed, so the soil can breathe. For the citrus that faces the old window.",
    image: "/images/keepsakes/bowl.jpg",
    createdAt: now - 18 * hour,
  },
  {
    id: "k4",
    dwellingId: "sable",
    fromId: "elena",
    kind: "silver",
    note: "A frame of your hands setting type. Nothing happens. Then it does.",
    image: "/images/keepsakes/silver.jpg",
    createdAt: now - 11 * hour,
  },
  {
    id: "k5",
    dwellingId: "rafi",
    fromId: "sable",
    kind: "page",
    note: "Printed the matchbook poem in 14pt Caslon. Two copies. One is for the roof.",
    image: "/images/keepsakes/page.jpg",
    createdAt: now - 16 * hour,
  },
  {
    id: "k6",
    dwellingId: "kai",
    fromId: "aya",
    kind: "crumb",
    note: "Fennel crust. For steam hour. I sat. I did not rush.",
    image: "/images/keepsakes/crumb.jpg",
    createdAt: now - 6 * hour,
  },
  {
    id: "k7",
    dwellingId: "jonah",
    fromId: "leo",
    kind: "leaf",
    note: "Pressed in the meadow ledger. The fern did not startle.",
    image: "/images/keepsakes/leaf.jpg",
    createdAt: now - 22 * hour,
  },
  {
    id: "k8",
    dwellingId: "elena",
    fromId: "rafi",
    kind: "star",
    note: "For the chair in the red light. I stayed until my eyes changed.",
    image: "/images/keepsakes/star.jpg",
    createdAt: now - 9 * hour,
  },
  {
    id: "k9",
    dwellingId: "mira",
    fromId: "sable",
    kind: "type",
    note: "The word GUEST, printed backwards so you can read it in clay.",
    image: "/images/keepsakes/type.jpg",
    createdAt: now - 40 * hour,
  },
  {
    id: "k10",
    dwellingId: "you",
    fromId: "mira",
    kind: "thread",
    note: "Welcome. The floor is already clay. You do not have to be useful.",
    image: "/images/keepsakes/thread.jpg",
    createdAt: now - 1 * hour,
  },
];

export const hearths: Hearth[] = [
  {
    id: "kept",
    title: "What did you keep this week?",
    prompt:
      "Not what you made. What you refused to throw away. Pass the object, or the sentence, around the fire.",
    hostId: "mira",
    neighborhoodId: "conservatory",
    cover: "/images/hearths/kept.jpg",
    startsAt: now - 40 * 60 * 1000,
    durationMin: 180,
    seated: ["mira", "leo", "sable", "kai"],
  },
  {
    id: "night-bread",
    title: "Night bread",
    prompt:
      "The ovens are on. Sit at the marble. You may speak or you may be warm. Both count as presence.",
    hostId: "aya",
    neighborhoodId: "hearth-grain",
    cover: "/images/hearths/night-bread.jpg",
    startsAt: now - 25 * 60 * 1000,
    durationMin: 240,
    seated: ["aya", "kai", "jonah"],
  },
  {
    id: "letters",
    title: "Letters we never sent",
    prompt:
      "Bring a sentence you could not give to its person. We will set some of them in type. The rest we will burn.",
    hostId: "sable",
    neighborhoodId: "night-terrace",
    cover: "/images/hearths/letters.jpg",
    startsAt: now + 2 * hour,
    durationMin: 120,
    seated: ["sable", "elena", "rafi"],
  },
  {
    id: "walk",
    title: "A walk for people who don't want to talk",
    prompt:
      "Meet at the meadow path. Headphones optional. The point is to be beside someone without performing company.",
    hostId: "jonah",
    neighborhoodId: "meadow-edge",
    cover: "/images/hearths/walk.jpg",
    startsAt: now + 5 * hour,
    durationMin: 90,
    seated: ["jonah", "leo"],
  },
  {
    id: "steam",
    title: "Tea at steam hour",
    prompt:
      "Four o'clock. The first cup is for the room. The second is for whatever you have been steeping.",
    hostId: "kai",
    neighborhoodId: "hearth-grain",
    cover: "/images/hearths/steam.jpg",
    startsAt: now - 10 * 60 * 1000,
    durationMin: 90,
    seated: ["kai", "aya", "mira"],
  },
  {
    id: "looking-up",
    title: "Looking up",
    prompt:
      "The roof holds whoever comes. No narration. If a satellite passes we may pretend, once.",
    hostId: "rafi",
    neighborhoodId: "night-terrace",
    cover: "/images/hearths/looking-up.jpg",
    startsAt: now + 8 * hour,
    durationMin: 150,
    seated: ["rafi", "elena"],
  },
];

export const embers: Ember[] = [
  {
    id: "e1",
    hearthId: "kept",
    fromId: "mira",
    body: "I kept the leaking bowl. It teaches my hands a slower circle.",
    createdAt: now - 28 * 60 * 1000,
  },
  {
    id: "e2",
    hearthId: "kept",
    fromId: "leo",
    body: "A label from a plant I never identified. I like not knowing its name.",
    createdAt: now - 21 * 60 * 1000,
  },
  {
    id: "e3",
    hearthId: "kept",
    fromId: "sable",
    body: "A drawer of Qs. They are waiting for a question worth asking.",
    createdAt: now - 14 * 60 * 1000,
  },
  {
    id: "e4",
    hearthId: "night-bread",
    fromId: "aya",
    body: "Fennel tonight. Two loaves on the sill. The marble is warm.",
    createdAt: now - 18 * 60 * 1000,
  },
  {
    id: "e5",
    hearthId: "night-bread",
    fromId: "kai",
    body: "I brought the leftover steam-hour blend. It tastes like a field after fire.",
    createdAt: now - 12 * 60 * 1000,
  },
  {
    id: "e6",
    hearthId: "night-bread",
    fromId: "jonah",
    body: "Sitting. Not talking. The oven is doing the speaking.",
    createdAt: now - 6 * 60 * 1000,
  },
  {
    id: "e7",
    hearthId: "steam",
    fromId: "kai",
    body: "First cup poured. The stool is empty and that is correct.",
    createdAt: now - 8 * 60 * 1000,
  },
  {
    id: "e8",
    hearthId: "steam",
    fromId: "mira",
    body: "Clay under my nails in your cup. Sorry. Not sorry.",
    createdAt: now - 4 * 60 * 1000,
  },
];

export const letters: Letter[] = [
  {
    id: "l1",
    fromId: "mira",
    toId: YOU_ID,
    body: "I saw a new light on the atlas. The Clay Room has a guest wheel. You do not have to make anything. You can just sit with the unfinished bowl.",
    sentAt: now - 3 * hour,
    arrivesAt: now - 2.5 * hour,
    read: false,
  },
  {
    id: "l2",
    fromId: "kai",
    toId: YOU_ID,
    body: "Steam hour is four, whether or not you come. If you do, tell me something you have been steeping. If you don't, the first cup will still be for the room.",
    sentAt: now - 90 * 60 * 1000,
    arrivesAt: now - 70 * 60 * 1000,
    read: false,
  },
  {
    id: "l3",
    fromId: "jonah",
    toId: "aya",
    body: "I left a stone on your marble. It was warm from the chimney. I did not want to wake you to say I was there.",
    sentAt: now - 8 * hour,
    arrivesAt: now - 7 * hour,
    read: true,
  },
];

export function personById(id: string): Person | undefined {
  return people.find((p) => p.id === id);
}

export function neighborhoodById(id: string): Neighborhood | undefined {
  return neighborhoods.find((n) => n.id === id);
}

export function hearthStatus(h: Hearth, at = Date.now()): "live" | "soon" | "ember" {
  const end = h.startsAt + h.durationMin * 60 * 1000;
  if (at < h.startsAt) return "soon";
  if (at < end) return "live";
  return "ember";
}
