/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldRouteImport } from './routes/_world'
import { Route as AboutRouteImport } from './routes/about'
import { Route as WorldArrivalsRouteImport } from './routes/_world/arrivals'
import { Route as WorldAtlasRouteImport } from './routes/_world/atlas'
import { Route as WorldCreateRouteImport } from './routes/_world/create'
import { Route as WorldDiscoverRouteImport } from './routes/_world/discover'
import { Route as WorldGatherRouteImport } from './routes/_world/gather'
import { Route as WorldLettersRouteImport } from './routes/_world/letters'
import { Route as WorldMeRouteImport } from './routes/_world/me'
import { Route as WorldDwellIdRouteImport } from './routes/_world/dwell.$id'
import { Route as WorldHearthIdRouteImport } from './routes/_world/hearth.$id'
import { Route as WorldNeighborhoodIdRouteImport } from './routes/_world/neighborhood.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/_world',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldArrivalsRoute = WorldArrivalsRouteImport.update({
  id: '/arrivals',
  path: '/arrivals',
  getParentRoute: () => WorldRoute,
} as any)
const WorldAtlasRoute = WorldAtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => WorldRoute,
} as any)
const WorldCreateRoute = WorldCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => WorldRoute,
} as any)
const WorldDiscoverRoute = WorldDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => WorldRoute,
} as any)
const WorldGatherRoute = WorldGatherRouteImport.update({
  id: '/gather',
  path: '/gather',
  getParentRoute: () => WorldRoute,
} as any)
const WorldLettersRoute = WorldLettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => WorldRoute,
} as any)
const WorldMeRoute = WorldMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => WorldRoute,
} as any)
const WorldDwellIdRoute = WorldDwellIdRouteImport.update({
  id: '/dwell/$id',
  path: '/dwell/$id',
  getParentRoute: () => WorldRoute,
} as any)
const WorldHearthIdRoute = WorldHearthIdRouteImport.update({
  id: '/hearth/$id',
  path: '/hearth/$id',
  getParentRoute: () => WorldRoute,
} as any)
const WorldNeighborhoodIdRoute = WorldNeighborhoodIdRouteImport.update({
  id: '/neighborhood/$id',
  path: '/neighborhood/$id',
  getParentRoute: () => WorldRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arrivals': typeof WorldArrivalsRoute
  '/atlas': typeof WorldAtlasRoute
  '/create': typeof WorldCreateRoute
  '/discover': typeof WorldDiscoverRoute
  '/gather': typeof WorldGatherRoute
  '/letters': typeof WorldLettersRoute
  '/me': typeof WorldMeRoute
  '/dwell/$id': typeof WorldDwellIdRoute
  '/hearth/$id': typeof WorldHearthIdRoute
  '/neighborhood/$id': typeof WorldNeighborhoodIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arrivals': typeof WorldArrivalsRoute
  '/atlas': typeof WorldAtlasRoute
  '/create': typeof WorldCreateRoute
  '/discover': typeof WorldDiscoverRoute
  '/gather': typeof WorldGatherRoute
  '/letters': typeof WorldLettersRoute
  '/me': typeof WorldMeRoute
  '/dwell/$id': typeof WorldDwellIdRoute
  '/hearth/$id': typeof WorldHearthIdRoute
  '/neighborhood/$id': typeof WorldNeighborhoodIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_world': typeof WorldRouteWithChildren
  '/about': typeof AboutRoute
  '/_world/arrivals': typeof WorldArrivalsRoute
  '/_world/atlas': typeof WorldAtlasRoute
  '/_world/create': typeof WorldCreateRoute
  '/_world/discover': typeof WorldDiscoverRoute
  '/_world/gather': typeof WorldGatherRoute
  '/_world/letters': typeof WorldLettersRoute
  '/_world/me': typeof WorldMeRoute
  '/_world/dwell/$id': typeof WorldDwellIdRoute
  '/_world/hearth/$id': typeof WorldHearthIdRoute
  '/_world/neighborhood/$id': typeof WorldNeighborhoodIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/arrivals'
    | '/atlas'
    | '/create'
    | '/discover'
    | '/gather'
    | '/letters'
    | '/me'
    | '/dwell/$id'
    | '/hearth/$id'
    | '/neighborhood/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/arrivals'
    | '/atlas'
    | '/create'
    | '/discover'
    | '/gather'
    | '/letters'
    | '/me'
    | '/dwell/$id'
    | '/hearth/$id'
    | '/neighborhood/$id'
  id:
    | '__root__'
    | '/'
    | '/_world'
    | '/about'
    | '/_world/arrivals'
    | '/_world/atlas'
    | '/_world/create'
    | '/_world/discover'
    | '/_world/gather'
    | '/_world/letters'
    | '/_world/me'
    | '/_world/dwell/$id'
    | '/_world/hearth/$id'
    | '/_world/neighborhood/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorldRoute: typeof WorldRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_world': {
      id: '/_world'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_world/arrivals': {
      id: '/_world/arrivals'
      path: '/arrivals'
      fullPath: '/arrivals'
      preLoaderRoute: typeof WorldArrivalsRouteImport
      parentRoute: typeof WorldRoute
    }
    '/_world/atlas': {
      id: '/_world/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof WorldAtlasRouteImport
      parentRoute: typeof WorldRoute
    }
    '/_world/create': {
      id: '/_world/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof WorldCreateRouteImport
      parentRoute: typeof WorldRoute
    }
    '/_world/discover': {
      id: '/_world/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof WorldDiscoverRouteImport
      parentRoute: typeof WorldRoute
    }
    '/_world/gather': {
      id: '/_world/gather'
      path: '/gather'
      fullPath: '/gather'
      preLoaderRoute: typeof WorldGatherRouteImport
      parentRoute: typeof WorldRoute
    }
    '/_world/letters': {
      id: '/_world/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof WorldLettersRouteImport
      parentRoute: typeof WorldRoute
    }
    '/_world/me': {
      id: '/_world/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof WorldMeRouteImport
      parentRoute: typeof WorldRoute
    }
    '/_world/dwell/$id': {
      id: '/_world/dwell/$id'
      path: '/dwell/$id'
      fullPath: '/dwell/$id'
      preLoaderRoute: typeof WorldDwellIdRouteImport
      parentRoute: typeof WorldRoute
    }
    '/_world/hearth/$id': {
      id: '/_world/hearth/$id'
      path: '/hearth/$id'
      fullPath: '/hearth/$id'
      preLoaderRoute: typeof WorldHearthIdRouteImport
      parentRoute: typeof WorldRoute
    }
    '/_world/neighborhood/$id': {
      id: '/_world/neighborhood/$id'
      path: '/neighborhood/$id'
      fullPath: '/neighborhood/$id'
      preLoaderRoute: typeof WorldNeighborhoodIdRouteImport
      parentRoute: typeof WorldRoute
    }
  }
}

interface WorldRouteChildren {
  WorldArrivalsRoute: typeof WorldArrivalsRoute
  WorldAtlasRoute: typeof WorldAtlasRoute
  WorldCreateRoute: typeof WorldCreateRoute
  WorldDiscoverRoute: typeof WorldDiscoverRoute
  WorldGatherRoute: typeof WorldGatherRoute
  WorldLettersRoute: typeof WorldLettersRoute
  WorldMeRoute: typeof WorldMeRoute
  WorldDwellIdRoute: typeof WorldDwellIdRoute
  WorldHearthIdRoute: typeof WorldHearthIdRoute
  WorldNeighborhoodIdRoute: typeof WorldNeighborhoodIdRoute
}

const WorldRouteChildren: WorldRouteChildren = {
  WorldArrivalsRoute: WorldArrivalsRoute,
  WorldAtlasRoute: WorldAtlasRoute,
  WorldCreateRoute: WorldCreateRoute,
  WorldDiscoverRoute: WorldDiscoverRoute,
  WorldGatherRoute: WorldGatherRoute,
  WorldLettersRoute: WorldLettersRoute,
  WorldMeRoute: WorldMeRoute,
  WorldDwellIdRoute: WorldDwellIdRoute,
  WorldHearthIdRoute: WorldHearthIdRoute,
  WorldNeighborhoodIdRoute: WorldNeighborhoodIdRoute,
}

const WorldRouteWithChildren = WorldRoute._addFileChildren(WorldRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorldRoute: WorldRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
